metadata:
  name: customer-churn-predictor3
  labels:
    team: testing team2
    owner: team@gmail.com
  annotations:
    notes: Testing env v1
spec:
  serving:
    variants:
      - name: v1
        endpoint: http://customer-churn-predictor3-v1.ml.svc.cluster.local:8080
        weight: 100
  timeout: 5s
  rate_limit:
    rps: 100
