metadata:
  name: p-o-i-1
  labels:
    team: poi1
    owner: poi1@gmail.com
  annotations:
    notes: testing
spec:
  serving:
    variants:
      - name: v1
        endpoint: http://p-o-i-1-v1.ml.svc.cluster.local:8080
        weight: 100
  timeout: 5s
  rate_limit:
    rps: 100
