metadata:
  name: test
  labels:
    team: testing
    owner: vats.amankumarjha2002@gmail.com
  annotations:
    notes: test
spec:
  serving:
    variants:
      - name: v1
        endpoint: http://test-v1.ml.svc.cluster.local:8080
        weight: 100
  timeout: 5s
  rate_limit:
    rps: 100
